### Create User
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "name":"ravi",
    "email":"ravi@mail.com",
    "dateOfBirth":"2000-09-12",
    "mobileNumber":9999999
}

### Read all Users
GET http://localhost:4000/user-api/users

### Read a User by ID
GET http://localhost:4000/user-api/users/69a69425bfe2b730c3b21f32

### Delete a User by ID
DELETE http://localhost:4000/user-api/users/69a69425bfe2b730c3b21f32

### Activate User
PATCH http://localhost:4000/user-api/users/69a69425bfe2b730c3b21f32